### ISSUE TITLE
maquettes

### ISSUE THREAD

**Issue by JaKa69** [mesi-commerce/mesi_front#1]
réaliser les maquêtes de l'application
https://design.penpot.app/#/workspace/75aa5258-9a82-8002-8003-89aff736e1aa/75aa5258-9a82-8002-8003-89b041bf72b1?page-id=d73b834e-8806-80c9-8003-89ddda8a86fc

**Comment by libap** [comment]
Maquette quasiment complète et accessible par tous avec un compte figma avec le mail de l'ipi:  [https://www.figma.com/file/CSzhDZzRvgjbuZOwPIphwb/Maquette?type=design&node-id=0%3A1&mode=design&t=2WpjTOUDQ5N8NpwZ-1](url)
